<script lang="ts">
  import type {TextAppearance} from "./textRaster";
  let {layer,fonts,presets,width,language,onchange,onfont,onpreset}:{layer:TextAppearance;fonts:{name:string;path:string}[];presets:{id:string;name:string}[];width:number;language:"tr"|"en";onchange:(patch:Partial<TextAppearance>)=>void;onfont:(path:string)=>Promise<void>;onpreset:(id:string)=>Promise<void>}=$props();
  let preset=$state("");
  const tr=$derived(language==="tr");
  const sliders=[{key:"size",en:"Font size",tr:"Yazı boyutu",min:8,max:600},{key:"opacity",en:"Opacity",tr:"Saydamlık",min:0,max:100}] as const;
</script>
{#if presets.length}<div class="text-preset-row"><select aria-label={tr?"Watermark preseti":"Watermark preset"} bind:value={preset}><option value="">{tr?"Text preseti seç":"Choose Text preset"}</option>{#each presets as item}<option value={item.id}>{item.name}</option>{/each}</select><button class="ghost" disabled={!preset} onclick={()=>onpreset(preset)}>{tr?"Uygula":"Apply"}</button></div>{/if}
<label class="field watermark-text-field"><span>{tr?"Yazı":"Watermark text"}</span><textarea rows="2" placeholder={tr?"Watermark yazını gir…":"Enter your watermark…"} value={layer.text} oninput={event=>onchange({text:event.currentTarget.value})}></textarea></label>
<details class="watermark-appearance"><summary>{tr?"Görünüm ayarları":"Appearance settings"}</summary>
  <label class="field"><span>{tr?"Yazı tipi":"Font"}</span><select value={layer.font_path} onchange={event=>onfont(event.currentTarget.value)}>{#each fonts as font}<option value={font.path}>{font.name}</option>{/each}</select></label>
  {#each sliders as item}{#if !item.key.startsWith("background_")||layer.background}<label class="watermark-slider"><span>{tr?item.tr:item.en}<small>{Math.round(layer[item.key])}</small></span><input aria-label={tr?item.tr:item.en} type="range" min={Math.min(item.min,layer[item.key])} max={Math.max(item.max,layer[item.key])} step="1" value={layer[item.key]} oninput={event=>onchange({[item.key]:Number(event.currentTarget.value)})}></label>{/if}{/each}
  <label class="watermark-color"><span>{tr?"Renk":"Color"}</span><input aria-label={tr?"Renk":"Color"} type="color" value={layer.color} oninput={event=>onchange({color:event.currentTarget.value})}></label>
  <div class="watermark-centering"><button class="ghost" onclick={()=>onchange({x:50,y:50,align:"center"})}>{tr?"Ortala":"Center watermark"}</button><button class="ghost" onclick={()=>onchange({x:50,align:"center"})}>{tr?"Yatay ortala":"Center horizontally"}</button></div>
</details>
<small>{tr?"Çıktı önizlemesinde sürükle; düz taşımak için Shift basılı tut. Köşeden boyutlandır. Gelişmiş görünümü Text’te preset olarak kaydedip burada uygula.":"Drag in output preview; hold Shift to lock movement to one axis. Resize from the corner. For advanced styling, save a preset in Text and apply it here."}</small>
<style>.watermark-text-field textarea{display:block;box-sizing:border-box;width:100%;min-height:64px;max-height:180px;resize:vertical;padding:10px 12px;border:1px solid var(--border);border-radius:7px;background:var(--surface-2);color:var(--text);font:400 12px/1.5 var(--sans);outline:none;transition:border-color .15s,box-shadow .15s}.watermark-text-field textarea:focus{border-color:var(--blue);box-shadow:0 0 0 2px color-mix(in srgb,var(--blue) 15%,transparent)}.watermark-text-field textarea::placeholder{color:var(--muted)}.watermark-centering{display:flex;gap:6px;flex-wrap:wrap}.watermark-centering button{flex:1}.watermark-appearance{font-size:11px}.watermark-appearance summary{cursor:pointer;margin:8px 0}.watermark-appearance .field,.watermark-appearance .watermark-slider{margin:12px 0}.watermark-color{display:flex;align-items:center;justify-content:space-between;margin:8px 0}.watermark-color input{width:40px;height:28px;padding:0}small{font-size:10px;color:var(--muted)}</style>
